#!/usr/bin/perl -w

#   compare_tempo -- compare tempo outputs from two files, or from two
#                    versions of tempo

#   see usage_die below for usage

$tpo1default = "tempo";
$tpo2default = "tempo";

($file1, $file2, $tpo1, $tpo2, $env1, $env2, $dir1, $dir2, $runtpo) = 
        compare_tempo_command_line_parse($tpo1default,$tpo2default,@ARGV);

die "Error: file $file1 does not exist\n" if (! -e $file1);
die "Error: file $file2 does not exist\n" if (! -e $file2);

if ($runtpo) { # first tempo run; open par file

  if ($env1 eq "") {
    if ($dir1 eq "") {
      system ("$tpo1 $file1 2>&1 > /dev/null\n");
    } else {
      system ("cd $dir1; $tpo1 $file1 2>&1 > /dev/null\n");
    }
  } else {
    if ($dir1 eq "") {
      system ("export TEMPO; TEMPO=$env1; $tpo1 $file1 2>&1 > /dev/null\n");
    } else {
      system ("cd $dir1;export TEMPO;TEMPO=$env1;$tpo1 $file1 2>&1 >/dev/null\n");
    }
  }

  ($chisqr1,$dof1,$parfile) = &tempo_lis_info($dir1);

  open (A,$parfile);

} else {       # pre-existing first par file

  open (A,$file1); 

}

@a = <A>;
foreach $i (0..$#a) {
  chop $a[$i];
}
close A;

if ($runtpo) { # second tempo run; open par file

  system ("rm $parfile\n");  # get rid of any pre-existing par file

  if ($env2 eq "") {
    if ($dir2 eq "") {
      system ("$tpo2 $file2 2>&1 > /dev/null\n");
    } else {
      system ("cd $dir2; $tpo2 $file2 2>&1 > /dev/null\n");
    }
  } else {
    if ($dir2 eq "") {
      system ("export TEMPO; TEMPO=$env2; $tpo2 $file2 2>&1 > /dev/null\n");
    } else {
      system ("cd $dir2;export TEMPO;TEMPO=$env2;$tpo2 $file2 2>&1 >/dev/null\n");
    }
  }

  ($chisqr2,$dof2,$parfile) = &tempo_lis_info($dir2);

  open (A,$parfile);

} else {       # pre-existing first par file

  open (A,$file2); 

}

@b = <A>;
foreach $i (0..$#b) {
  chop $b[$i];
}
close A;

print "\n";

  print '-'x19 . 'tempo run a' . '-'x19 . '      ';
  print '-'x19 . 'tempo run b' . '-'x19 . "\n";
if ($runtpo) {
  $out = ' 'x 110;
  substr($out,0,length($file1)+6) = "file: ".$file1;
  substr($out,55,length($file2)+6) = "file: ".$file2;
  print "$out\n";
  $out = ' 'x 110;
  substr($out,0,length($dir1)+11) = "directory: ".$dir1;
  substr($out,55,length($dir2)+11) = "directory: ".$dir2;
  print "$out\n";
  $out = ' 'x 110;
  substr($out,0,length($tpo1)+7) = "tempo: ".$tpo1;
  substr($out,55,length($tpo2)+7) = "tempo: ".$tpo2;
  print "$out\n";
  $out = ' 'x 110;
  substr($out,0,length($env1)+8) = "\$TEMPO: ".$env1;
  substr($out,55,length($env2)+8) = "\$TEMPO: ".$env2;
} else {
  $out = ' 'x 110;
  substr($out,0,length($file1)+10) = "par file: ".$file1;
  substr($out,55,length($file2)+10) = "par file: ".$file2;
}
$out = $out . "  "."     b-a     ";
$out = $out . "  "." (b-a)/max(siga,sigb)";
$out = $out . "  "."   (b-a)/[(a+b)/2]";
$out = $out . "  sigb/siga";
print "$out\n";
print "\n";

$idxa = 0; 
$idxb = 0;
while ($idxa<=$#a && $idxb<=$#b) {
  ($aname) = (split(" ",$a[$idxa]))[0];
  ($bname) = (split(" ",$b[$idxb]))[0];
  if ($aname ne $bname) {
    $matchflag = 0;
  A: foreach $i ($idxb+1..$#b) {
      $bnamex = (split(" ",$b[$i]))[0];
      if ($bnamex eq $aname) {
        foreach $j($idxb..$i-1) {
          $out = ' 'x 110;  
          substr($out,55,length($b[$j])) = $b[$j];
          print "$out\n";
        }
        $matchflag = 1;
        $idxb=$i;
        last A;
      }
    }
    if ($matchflag==0) {
    B: foreach $i ($idxa+1..$#a) {
        $anamex = (split(" ",$a[$i]))[0];
        if ($anamex eq $bname) {
          foreach $j ($idxa..$i-1) {
            $out = ' ' x 110;
            substr($out,0,length($a[$j])) = $a[$j];
            print "$out\n";
          }
          $matchflag = 1;
          $idxa=$i;
          last B;
        }
      }
    }
    if ($matchflag==0) {
      print "cannot reconcile parameter files starting with these lines:\n";
      $out = ' 'x 110;  
      substr($out,0,length($a[$idxa])) = $a[$idxa];
      substr($out,55,length($b[$idxb])) = $b[$idxb];
    }
  }
  $out = ' 'x 110;  
  substr($out,0,length($a[$idxa])) = $a[$idxa];
  substr($out,55,length($b[$idxb])) = $b[$idxb];
  $a[$idxa] =~ s/D/E/g;
  $b[$idxb] =~ s/D/E/g;
  @tmp = split(" ",$a[$idxa]);
  if ($tmp[0] eq "JUMP" && $tmp[1]=~/^/)  {
    ($atmp1,$aflag,$aerr) = @tmp[3,4,5];
  } else {
    ($atmp1,$aflag,$aerr) = @tmp[1,2,3];
  }
  @tmp = split(" ",$b[$idxb]);
  if ($tmp[0] eq "JUMP" && $tmp[1]=~/^/)  {
    ($btmp1,$bflag,$berr) = (split(" ",$b[$idxb]))[3,4,5];
  } else {
    ($btmp1,$bflag,$berr) = (split(" ",$b[$idxb]))[1,2,3];
  }

  if (defined($aflag) && defined($bflag) && $aflag>0 && $bflag>0) {    
    @atmp = split(":",$atmp1);   #this fixes entries of the form aa:bb:cc
    @btmp = split(":",$btmp1);   #but also works for single number-entries
    $aparam = 0.;
    foreach $i (0..$#atmp) {
      $aparam = 60*$aparam + shift(@atmp);
    }
    $bparam = 0.;
    foreach $i (0..$#btmp) {
      $bparam = 60*$bparam + shift(@btmp);
    }
    $diff = $bparam-$aparam;
    $diffx = $diff/(0.5*($aparam+$bparam));
    $diffsig = abs($diff)/$aerr if ($berr<=$aerr);
    $diffsig = abs($diff)/$berr if ($berr>$aerr);
    $ratsig = 0;
    $ratsig = $berr/$aerr if ($aerr>0);
    $out = $out . sprintf("  %13.6e  %20.15f  %20.15f  %7.3f",$diff,$diffsig,$diffx,$ratsig);
  }
  print "$out\n";
  $idxa++;
  $idxb++;
}
if ($idxa<=$#a) {
  foreach $j ($idxa..$#a) {
    $out = ' ' x 110;
    substr($out,0,length($a[$j])) = $a[$j];
    print "$out\n";
  }
}
if ($idxb<=$#b) {
  foreach $j ($idxb..$#b) {
    $out = ' ' x 110;
    substr($out,55,length($b[$j])) = $b[$j];
    print "$out\n";
  }
}

if ($runtpo) {
  print "\n";
  printf "CHISQR    %16.2f".(" "x29)."CHISQR     %16.2f\n", $chisqr1, $chisqr2;
  printf "DOF       %16d"  .(" "x29)."DOF        %16d\n",   $dof1, $dof2;
  printf "CHISQR/DOF%16.2f".(" "x29)."CHISQR/DOF %16.2f\n", $chisqr1/$dof1, $chisqr2/$dof2;
}

#-----------------------------------------

sub tempo_lis_info {
  my($dir) = @_;
  my($psr);
  my($chisqr,$dof,$parfile);
  $dir = "." if ($dir eq "");
  open (AAA,"$dir/tempo.lis");
  $psr = "error"; # default
  ($chisqr,$dof) = (-1,-1);  # default
  while (<AAA>) {
    if (/Assumed parameters/) {      
      $psr = (split)[4];
    }
    if (/Chisqr\/nfree/) {
      $_ =~ s/=/ = /g;
      $_ =~ s/nfree:/nfree: /g;
#      ($chisqr,$dof) = (split)[1,2];
      ($dof,$rchisqr) = (split)[2,4];
      $chisqr = $rchisqr*$dof;
    }
  }
  close (AAA);
  $parfile = $dir . "/" . $psr . ".par";
  ($chisqr, $dof, $parfile);

}

#-----------------------------------------

sub compare_tempo_command_line_parse {

  # parse input line
  #  
  # calling parameters:
  #    -- $tpo1default
  #    -- $tpo2default
  #    -- command line parameters from @ARGV
  #  
  #
  # the parsing code is set up to allow for:
  #    -- flags of the form '-a'
  #    -- flags with parameters of the form '-axxxx'
  #    -- parameters without flags, simply 'xxxx' (but see below)
  #
  # Parameters without flags are accumulated in array @param.  

  my($tpo1default) = shift;   # first parameter of subroutine
  my($tpo2default) = shift;   # second parameter of subroutine

  my($usage) = 
  "\n".
  "Use:\n".
  "    compare_tempo file1 [file2] (options)\n".
  "What it does:\n".
  "    default: Run tempo twice (on two files, or two versions of tempo); compare .par files\n".
  "    -p mode: Compare .par files without actually running tempo\n".
  "Parameters:\n".
  "    file1 = tempo input file (or par file in -p mode) for first run\n".
  "    file2 = tempo input file (or par file in -p mode) for second run [default=same as file1]\n".
  "Options:\n".
  "   -aXXX   = tempo executable, first run    [default=$tpo1default]\n".
  "   -bXXX   = tempo executable, second run   [default=$tpo2default]\n".
  "   -cXXX   \$TEMPO env variable, first run  [default=preexisting \$TEMPO]\n".
  "   -dXXX   \$TEMPO env variable, second run [default=preexisting \$TEMPO]\n".
  "   -eXXX   = working directory, first run   [default=current working directory]\n".
  "   -fXXX   = working directory, second run  [default=current working directory]\n".
  "   -h      = help message\n".
  "   -p      = don't run tempo; read file1 and file2 as tempo .par files\n".
  "\n";

  my($f);
  my($par);
  my(@param)=();

  # defaults

  my($env1) = "";
  my($env2) = "";
  my($dir1) = "";
  my($dir2) = "";
  my($tpo1) = $tpo1default;
  my($tpo2) = $tpo2default;
  my($runtpo) = 1;

  foreach $par (@_) {
    if ($par=~/^-/) {           # flags
      $par = substr($par,1);      #   strip off the leading "-"
      while ($par ne "") {      #   loop through the string
        $f = substr($par,0,1);  #     strip off the current flag
        $par = substr($par,1);    #     process flags:
        if ($f eq "a")      {#       -a
          $tpo1 = $par;
          last;
        } elsif ($f eq "b") {#       -f
          $tpo2 = $par;
          last;
        } elsif ($f eq "c") {#       -f
          $env1 = $par;
          last;
        } elsif ($f eq "d") {#       -f
          $env2 = $par;
          last;
        } elsif ($f eq "e") {#       -f
          $dir1 = $par;
          last;
        } elsif ($f eq "f") {#       -f
          $dir2 = $par;
          last;
        } elsif ($f eq "h") {#       -h
          die $usage;
        } elsif ($f eq "p") {#       -t
          $runtpo = 0;
        }  else {            #       invalid flag
          print "\nERROR: Invalid flag -$f\n\n";
          die $usage;
        }
      }
    } else {                  # parameters
      push @param, $par;        #   push onto parameter list
    }
  }

  if ($#param<0 || $#param>1) {
    print "\nERROR: following parameters have no meaning: ",join(" ",@param),"\n";
    die $usage;
  }
  my($file1) = $param[0];
  my($file2) = $file1;
  $file2 = $param[1] if ($#param>0);

  return $file1, $file2, $tpo1, $tpo2, $env1, $env2, $dir1, $dir2, $runtpo;
}

