c      $Id$
      SUBROUTINE PROPMO(FA,FD,EA,ED,ARA,ADC)
      IMPLICIT REAL*8 (A-H,O-Z)
	parameter (TWOPI=6.28318530717958648d0)

      FDA=DABS(FD)
C###      FAC=FA*DCOS(ADC)
	fac=fa
      FAA=DABS(FAC)
      EAC=EA*DCOS(ADC)
C  PM (PMERR) IS SPACE PROPER MOTION
C  PHI (PHIERR) IS POSITION ANGLE OF SPACE VECTOR
C  GALANG IS POSITION ANGLE IN GALACTIC COORDINATE
      PM=DSQRT(FD**2+FAC**2)
      PMERR=(FDA*ED+FAA*EAC)/PM
      PHI=DATAN2(FAC,FD)
      IF (PHI.LT.0.) PHI=PHI+TWOPI
      PHIERR=(FAA*ED+FDA*EAC)/PM**2
      PHI=PHI*180./3.1415926
      PHIERR=PHIERR*180./3.1415926
C  CONVERT ANGLE PHI FROM CELESTIAL COORD TO GALACTOC CO.
      CALL GALCO (ARA,ADC,Q,PHI,GALANG)
      WRITE(31,10) PM,PMERR,PHI,PHIERR,GALANG
10    FORMAT(/'Composite proper motion =',f9.4,' +/-',f9.4,' mas/yr'/
     +  'Position angle:  Celestial:',F8.2,' +/-',F7.2,' deg',
     +  '  Galactic:',F8.2,' deg')

      RETURN
      END
